# Generated by Django 5.1.2 on 2025-06-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_emailscontacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailsContacto',
            new_name='EmailsContactos',
        ),
        migrations.RenameField(
            model_name='publicaciones',
            old_name='ubicacion',
            new_name='latitud',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='longitud',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
