# Generated by Django 5.1.2 on 2025-06-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_emailscontacto_emailscontactos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='estado_publicacion',
            field=models.CharField(choices=[('publicada', 'Publicada'), ('pendiente', 'Pendiente'), ('rechazada', 'Rechazada')], default='pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='img',
            field=models.CharField(default='https://www.repretel.com/wp-content/uploads/2021/07/Imagen-14_7_2021-15_57_59.jpg', max_length=100),
        ),
    ]
