# Generated by Django 5.2 on 2025-06-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_publicaciones_estado_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='img',
            field=models.CharField(max_length=100),
        ),
    ]
