# Generated by Django 5.1.2 on 2025-06-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_publicaciones_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
