# Generated by Django 5.2 on 2025-06-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_respuestacomentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestacomentarios',
            name='publicacion',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='api.publicaciones'),
            preserve_default=False,
        ),
    ]
