# Generated by Django 5.1.2 on 2025-06-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_calificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='puntaje',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
