# Generated by Django 5.1.2 on 2025-06-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_calificaciones_puntaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
