# Generated by Django 5.1.2 on 2025-06-23 16:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificaciones',
            unique_together={('usuario', 'publicacion')},
        ),
    ]
