# Generated by Django 5.2 on 2025-06-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='reporte',
            field=models.IntegerField(default=0),
        ),
    ]
