# Generated by Django 5.2 on 2025-06-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_publicaciones_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='prueba',
            field=models.IntegerField(default=0),
        ),
    ]
