# Generated by Django 5.1.2 on 2025-06-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_calificaciones_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificaciones',
            unique_together=set(),
        ),
    ]
