# Generated by Django 5.1.2 on 2025-06-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_calificaciones_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto_perfil',
            field=models.TextField(default='0'),
        ),
    ]
