# Generated by Django 5.2 on 2025-06-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_publicaciones_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='prueba',
        ),
    ]
