# Generated by Django 5.1.2 on 2025-06-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_usuarios_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto_perfil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
