# Generated by Django 5.1.2 on 2025-06-24 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_usuarios_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificaciones',
            unique_together={('usuario', 'publicacion')},
        ),
    ]
