# Generated by Django 5.2 on 2025-06-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_publicaciones_prueba'),
        ('api', '0021_alter_calificaciones_unique_together'),
    ]

    operations = [
    ]
