# Generated by Django 5.2 on 2025-06-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20250625_0825'),
        ('api', '0022_merge_20250625_0832'),
    ]

    operations = [
    ]
