# Generated by Django 5.2 on 2025-06-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge_20250626_0804'),
        ('api', '0023_merge_20250626_0833'),
    ]

    operations = [
    ]
